# -*- coding: utf-8 -*-
"""Task2_LGMVIP..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SiX2thd9mhXRXssxUl4udE3EeBpMZT8o

***LGMVIP***

**DATA SCIENCE INTERNSHIP**

**TASK 2 | IMAGE TO PENCIL SKETCH**

Importing Library
"""

import numpy as np
import pandas as pd
import cv2 as cv
from google.colab.patches import cv2_imshow
from skimage import io
from PIL import Image
import matplotlib.pylab as plt

"""Reading Data onto Notebook"""

image1=io.imread("Cat.jpg")
cv2_imshow(image1)

"""Converting Image into GrayScale Image"""

greyscale1= cv.cvtColor(image1, cv.COLOR_BGR2GRAY)
cv2_imshow(greyscale1)

"""Inverting Image"""

inverted1 = 255 - greyscale1
cv2_imshow(inverted1)

"""Blurring the Image"""

blurred1 = cv.GaussianBlur(inverted1, (21, 21), 0)

"""Inverting the Blurred Image"""

inverted_blurred1 = 255 - blurred1
Sketch1 = cv.divide(greyscale1, inverted_blurred1, scale=256.0)
cv2_imshow(Sketch1)

"""Original vs Sketch"""

cv2_imshow(image1)
cv2_imshow(Sketch1)